export default function handler(req, res) {
   res.status(200).json( [
        {
          bodyPart: 'waist',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0001.gif',
          id: '0001',
          name: '3/4 sit-up',
          target: 'abs'
        },
        {
          bodyPart: 'waist',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0002.gif',
          id: '0002',
          name: '45° side bend',
          target: 'abs'
        },
        {
          bodyPart: 'waist',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0003.gif',
          id: '0003',
          name: 'air bike',
          target: 'abs'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1512.gif',
          id: '1512',
          name: 'all fours squad stretch',
          target: 'quads'
        },
        {
          bodyPart: 'waist',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0006.gif',
          id: '0006',
          name: 'alternate heel touchers',
          target: 'abs'
        },
        {
          bodyPart: 'back',
          equipment: 'cable',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0007.gif',
          id: '0007',
          name: 'alternate lateral pulldown',
          target: 'lats'
        },
        {
          bodyPart: 'lower legs',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1368.gif',
          id: '1368',
          name: 'ankle circles',
          target: 'calves'
        },
        {
          bodyPart: 'back',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/3293.gif',
          id: '3293',
          name: 'archer pull up',
          target: 'lats'
        },
        {
          bodyPart: 'chest',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/3294.gif',
          id: '3294',
          name: 'archer push up',
          target: 'chest'
        },
        {
          bodyPart: 'waist',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/2355.gif',
          id: '2355',
          name: 'arm slingers hanging bent knee legs',
          target: 'abs'
        },
        {
          bodyPart: 'waist',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/2333.gif',
          id: '2333',
          name: 'arm slingers hanging straight legs',
          target: 'abs'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/3214.gif',
          id: '3214',
          name: 'arms apart circular toe touch (male)',
          target: 'glutes'
        },
        {
          bodyPart: 'waist',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/3204.gif',
          id: '3204',
          name: 'arms overhead full sit-up (male)',
          target: 'abs'
        },
        {
          bodyPart: 'chest',
          equipment: 'leverage machine',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0009.gif',
          id: '0009',
          name: 'assisted chest dip (kneeling)',
          target: 'chest'
        },
        {
          bodyPart: 'waist',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0011.gif',
          id: '0011',
          name: 'assisted hanging knee raise',
          target: 'abs'
        },
        {
          bodyPart: 'waist',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0010.gif',
          id: '0010',
          name: 'assisted hanging knee raise with throw down',
          target: 'abs'
        },
        {
          bodyPart: 'lower legs',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1708.gif',
          id: '1708',
          name: 'assisted lying calves stretch',
          target: 'calves'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1709.gif',
          id: '1709',
          name: 'assisted lying glutes stretch',
          target: 'glutes'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1710.gif',
          id: '1710',
          name: 'assisted lying gluteus and piriformis stretch',
          target: 'glutes'
        },
        {
          bodyPart: 'waist',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0012.gif',
          id: '0012',
          name: 'assisted lying leg raise with lateral throw down',
          target: 'abs'
        },
        {
          bodyPart: 'waist',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0013.gif',
          id: '0013',
          name: 'assisted lying leg raise with throw down',
          target: 'abs'
        },
        {
          bodyPart: 'waist',
          equipment: 'medicine ball',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0014.gif',
          id: '0014',
          name: 'assisted motion russian twist',
          target: 'abs'
        },
        {
          bodyPart: 'back',
          equipment: 'leverage machine',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0015.gif',
          id: '0015',
          name: 'assisted parallel close grip pull-up',
          target: 'lats'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0016.gif',
          id: '0016',
          name: 'assisted prone hamstring',
          target: 'hamstrings'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1713.gif',
          id: '1713',
          name: 'assisted prone lying quads stretch',
          target: 'quads'
        },
        {
          bodyPart: 'waist',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1714.gif',
          id: '1714',
          name: 'assisted prone rectus femoris stretch',
          target: 'abs'
        },
        {
          bodyPart: 'back',
          equipment: 'leverage machine',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0017.gif',
          id: '0017',
          name: 'assisted pull-up',
          target: 'lats'
        },
        {
          bodyPart: 'chest',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1716.gif',
          id: '1716',
          name: 'assisted seated pectoralis major stretch with stability ball',
          target: 'chest'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1712.gif',
          id: '1712',
          name: 'assisted side lying adductor stretch',
          target: 'adductors'
        },
        {
          bodyPart: 'waist',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1758.gif',
          id: '1758',
          name: 'assisted sit-up',
          target: 'abs'
        },
        {
          bodyPart: 'back',
          equipment: 'leverage machine',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1431.gif',
          id: '1431',
          name: 'assisted standing chin-up',
          target: 'lats'
        },
        {
          bodyPart: 'back',
          equipment: 'leverage machine',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1432.gif',
          id: '1432',
          name: 'assisted standing pull-up',
          target: 'lats'
        },
        {
          bodyPart: 'upper arms',
          equipment: 'assisted',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0018.gif',
          id: '0018',
          name: 'assisted standing triceps extension (with towel)',
          target: 'triceps'
        },
        {
          bodyPart: 'upper arms',
          equipment: 'leverage machine',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0019.gif',
          id: '0019',
          name: 'assisted triceps dip (kneeling)',
          target: 'triceps'
        },
        {
          bodyPart: 'chest',
          equipment: 'leverage machine',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/2364.gif',
          id: '2364',
          name: 'assisted wide-grip chest dip (kneeling)',
          target: 'chest'
        },
        {
          bodyPart: 'cardio',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/3220.gif',
          id: '3220',
          name: 'astride jumps (male)',
          target: 'cardiovascular system'
        },
        {
          bodyPart: 'cardio',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/3672.gif',
          id: '3672',
          name: 'back and forth step',
          target: 'cardiovascular system'
        },
        {
          bodyPart: 'back',
          equipment: 'stability ball',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1314.gif',
          id: '1314',
          name: 'back extension on exercise ball',
          target: 'spine'
        },
        {
          bodyPart: 'back',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/3297.gif',
          id: '3297',
          name: 'back lever',
          target: 'upper back'
        },
        {
          bodyPart: 'back',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1405.gif',
          id: '1405',
          name: 'back pec stretch',
          target: 'lats'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1473.gif',
          id: '1473',
          name: 'backward jump',
          target: 'quads'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'body weight',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0020.gif',
          id: '0020',
          name: 'balance board',
          target: 'quads'
        },
        {
          bodyPart: 'upper arms',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0968.gif',
          id: '0968',
          name: 'band alternating biceps curl',
          target: 'biceps'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0969.gif',
          id: '0969',
          name: 'band alternating v-up',
          target: 'abs'
        },
        {
          bodyPart: 'back',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0970.gif',
          id: '0970',
          name: 'band assisted pull-up',
          target: 'lats'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0971.gif',
          id: '0971',
          name: 'band assisted wheel rollerout',
          target: 'abs'
        },
        {
          bodyPart: 'chest',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1254.gif',
          id: '1254',
          name: 'band bench press',
          target: 'chest'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0980.gif',
          id: '0980',
          name: 'band bent-over hip extension',
          target: 'glutes'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0972.gif',
          id: '0972',
          name: 'band bicycle crunch',
          target: 'abs'
        },
        {
          bodyPart: 'back',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0974.gif',
          id: '0974',
          name: 'band close-grip pulldown',
          target: 'lats'
        },
        {
          bodyPart: 'upper arms',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0975.gif',
          id: '0975',
          name: 'band close-grip push-up',
          target: 'triceps'
        },
        {
          bodyPart: 'upper arms',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0976.gif',
          id: '0976',
          name: 'band concentration curl',
          target: 'biceps'
        },
        {
          bodyPart: 'back',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/3117.gif',
          id: '3117',
          name: 'band fixed back close grip pulldown',
          target: 'lats'
        },
        {
          bodyPart: 'back',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/3116.gif',
          id: '3116',
          name: 'band fixed back underhand pulldown',
          target: 'lats'
        },
        {
          bodyPart: 'shoulders',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0977.gif',
          id: '0977',
          name: 'band front lateral raise',
          target: 'delts'
        },
        {
          bodyPart: 'shoulders',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0978.gif',
          id: '0978',
          name: 'band front raise',
          target: 'delts'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1408.gif',
          id: '1408',
          name: 'band hip lift',
          target: 'glutes'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0979.gif',
          id: '0979',
          name: 'band horizontal pallof press',
          target: 'abs'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0981.gif',
          id: '0981',
          name: 'band jack knife sit-up',
          target: 'abs'
        },
        {
          bodyPart: 'back',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0983.gif',
          id: '0983',
          name: 'band kneeling one arm pulldown',
          target: 'lats'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0985.gif',
          id: '0985',
          name: 'band kneeling twisting crunch',
          target: 'abs'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0984.gif',
          id: '0984',
          name: 'band lying hip internal rotation',
          target: 'glutes'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1002.gif',
          id: '1002',
          name: 'band lying straight leg raise',
          target: 'abs'
        },
        {
          bodyPart: 'upper arms',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0986.gif',
          id: '0986',
          name: 'band one arm overhead biceps curl',
          target: 'biceps'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0987.gif',
          id: '0987',
          name: 'band one arm single leg split squat',
          target: 'quads'
        },
        {
          bodyPart: 'back',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0988.gif',
          id: '0988',
          name: 'band one arm standing low row',
          target: 'upper back'
        },
        {
          bodyPart: 'chest',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0989.gif',
          id: '0989',
          name: 'band one arm twisting chest press',
          target: 'chest'
        },
        {
          bodyPart: 'back',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0990.gif',
          id: '0990',
          name: 'band one arm twisting seated row',
          target: 'upper back'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0991.gif',
          id: '0991',
          name: 'band pull through',
          target: 'glutes'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0992.gif',
          id: '0992',
          name: 'band push sit-up',
          target: 'abs'
        },
        {
          bodyPart: 'shoulders',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0993.gif',
          id: '0993',
          name: 'band reverse fly',
          target: 'delts'
        },
        {
          bodyPart: 'lower arms',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0994.gif',
          id: '0994',
          name: 'band reverse wrist curl',
          target: 'forearms'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0996.gif',
          id: '0996',
          name: 'band seated hip internal rotation',
          target: 'glutes'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1011.gif',
          id: '1011',
          name: 'band seated twist',
          target: 'abs'
        },
        {
          bodyPart: 'shoulders',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0997.gif',
          id: '0997',
          name: 'band shoulder press',
          target: 'delts'
        },
        {
          bodyPart: 'back',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1018.gif',
          id: '1018',
          name: 'band shrug',
          target: 'traps'
        },
        {
          bodyPart: 'upper arms',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0998.gif',
          id: '0998',
          name: 'band side triceps extension',
          target: 'triceps'
        },
        {
          bodyPart: 'lower legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0999.gif',
          id: '0999',
          name: 'band single leg calf raise',
          target: 'calves'
        },
        {
          bodyPart: 'lower legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1000.gif',
          id: '1000',
          name: 'band single leg reverse calf raise',
          target: 'calves'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1001.gif',
          id: '1001',
          name: 'band single leg split squat',
          target: 'quads'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1004.gif',
          id: '1004',
          name: 'band squat',
          target: 'glutes'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1003.gif',
          id: '1003',
          name: 'band squat row',
          target: 'glutes'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1005.gif',
          id: '1005',
          name: 'band standing crunch',
          target: 'abs'
        },
        {
          bodyPart: 'shoulders',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1022.gif',
          id: '1022',
          name: 'band standing rear delt row',
          target: 'delts'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1007.gif',
          id: '1007',
          name: 'band standing twisting crunch',
          target: 'abs'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1008.gif',
          id: '1008',
          name: 'band step-up',
          target: 'glutes'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1009.gif',
          id: '1009',
          name: 'band stiff leg deadlift',
          target: 'glutes'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1023.gif',
          id: '1023',
          name: 'band straight back stiff leg deadlift',
          target: 'glutes'
        },
        {
          bodyPart: 'back',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1010.gif',
          id: '1010',
          name: 'band straight leg deadlift',
          target: 'spine'
        },
        {
          bodyPart: 'shoulders',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1012.gif',
          id: '1012',
          name: 'band twisting overhead press',
          target: 'delts'
        },
        {
          bodyPart: 'lower legs',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1369.gif',
          id: '1369',
          name: 'band two legs calf raise - (band under both legs) v. 2',
          target: 'calves'
        },
        {
          bodyPart: 'back',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1013.gif',
          id: '1013',
          name: 'band underhand pulldown',
          target: 'lats'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1014.gif',
          id: '1014',
          name: 'band v-up',
          target: 'abs'
        },
        {
          bodyPart: 'waist',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1015.gif',
          id: '1015',
          name: 'band vertical pallof press',
          target: 'abs'
        },
        {
          bodyPart: 'lower arms',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1016.gif',
          id: '1016',
          name: 'band wrist curl',
          target: 'forearms'
        },
        {
          bodyPart: 'shoulders',
          equipment: 'band',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/1017.gif',
          id: '1017',
          name: 'band y-raise',
          target: 'delts'
        },
        {
          bodyPart: 'upper arms',
          equipment: 'barbell',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0023.gif',
          id: '0023',
          name: 'barbell alternate biceps curl',
          target: 'biceps'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'barbell',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0024.gif',
          id: '0024',
          name: 'barbell bench front squat',
          target: 'quads'
        },
        {
          bodyPart: 'chest',
          equipment: 'barbell',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0025.gif',
          id: '0025',
          name: 'barbell bench press',
          target: 'chest'
        },
        {
          bodyPart: 'upper legs',
          equipment: 'barbell',
          gifUrl: 'http://d205bpvrqc9yn1.cloudfront.net/0026.gif',
          id: '0026',
          name: 'barbell bench squat',
          target: 'quads'
        },
        {
          "bodyPart":"waist",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/2800.gif",
          "id":"2800",
          "name":"barbell sitted alternate leg raise (female)",
          "target":"abs",
        },
        {
          "bodyPart":"shoulders",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0100.gif",
          "id":"0100",
          "name":"barbell skier",
          "target":"delts",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0101.gif",
          "id":"0101",
          "name":"barbell speed squat",
          "target":"glutes",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/2810.gif",
          "id":"2810",
          "name":"barbell split squat v. 2",
          "target":"quads",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0102.gif",
          "id":"0102",
          "name":"barbell squat (on knees)",
          "target":"quads",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/2798.gif",
          "id":"2798",
          "name":"barbell squat jump step rear lunge",
          "target":"quads",
          },
          {
          "bodyPart":"waist",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0103.gif",
          "id":"0103",
          "name":"barbell standing ab rollerout",
          "target":"abs",
          },
          {
          "bodyPart":"lower arms",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0104.gif",
          "id":"0104",
          "name":"barbell standing back wrist curl",
          "target":"forearms",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0105.gif",
          "id":"0105",
          "name":"barbell standing bradford press",
          "target":"delts",
          },
          {
          "bodyPart":"lower legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1372.gif",
          "id":"1372",
          "name":"barbell standing calf raise",
          "target":"calves",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0106.gif",
          "id":"0106",
          "name":"barbell standing close grip curl",
          "target":"biceps",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1456.gif",
          "id":"1456",
          "name":"barbell standing close grip military press",
          "target":"delts",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/2414.gif",
          "id":"2414",
          "name":"barbell standing concentration curl",
          "target":"biceps",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0107.gif",
          "id":"0107",
          "name":"barbell standing front raise over head",
          "target":"delts",
          },
          {
          "bodyPart":"lower legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0108.gif",
          "id":"0108",
          "name":"barbell standing leg calf raise",
          "target":"calves",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0109.gif",
          "id":"0109",
          "name":"barbell standing overhead triceps extension",
          "target":"triceps",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0110.gif",
          "id":"0110",
          "name":"barbell standing reverse grip curl",
          "target":"biceps",
          },
          {
          "bodyPart":"lower legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0111.gif",
          "id":"0111",
          "name":"barbell standing rocking leg calf raise",
          "target":"calves",
          },
          {
          "bodyPart":"waist",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0112.gif",
          "id":"0112",
          "name":"barbell standing twist",
          "target":"abs",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1629.gif",
          "id":"1629",
          "name":"barbell standing wide grip biceps curl",
          "target":"biceps",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1457.gif",
          "id":"1457",
          "name":"barbell standing wide military press",
          "target":"delts",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0113.gif",
          "id":"0113",
          "name":"barbell standing wide-grip curl",
          "target":"biceps",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0114.gif",
          "id":"0114",
          "name":"barbell step-up",
          "target":"glutes",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0115.gif",
          "id":"0115",
          "name":"barbell stiff leg good morning",
          "target":"glutes",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0116.gif",
          "id":"0116",
          "name":"barbell straight leg deadlift",
          "target":"hamstrings",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0117.gif",
          "id":"0117",
          "name":"barbell sumo deadlift",
          "target":"glutes",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3305.gif",
          "id":"3305",
          "name":"barbell thruster",
          "target":"delts",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0120.gif",
          "id":"0120",
          "name":"barbell upright row",
          "target":"delts",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0119.gif",
          "id":"0119",
          "name":"barbell upright row v. 2",
          "target":"delts",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0121.gif",
          "id":"0121",
          "name":"barbell upright row v. 3",
          "target":"delts",
          },
          {
          "bodyPart":"chest",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0122.gif",
          "id":"0122",
          "name":"barbell wide bench press",
          "target":"chest",
          },
          {
          "bodyPart":"chest",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1258.gif",
          "id":"1258",
          "name":"barbell wide reverse grip bench press",
          "target":"chest",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0124.gif",
          "id":"0124",
          "name":"barbell wide squat",
          "target":"quads",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0123.gif",
          "id":"0123",
          "name":"barbell wide-grip upright row",
          "target":"delts",
          },
          {
          "bodyPart":"lower arms",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0126.gif",
          "id":"0126",
          "name":"barbell wrist curl",
          "target":"forearms",
          },
          {
          "bodyPart":"lower arms",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0125.gif",
          "id":"0125",
          "name":"barbell wrist curl v. 2",
          "target":"forearms",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"barbell",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0127.gif",
          "id":"0127",
          "name":"barbell zercher squat",
          "target":"glutes",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3212.gif",
          "id":"3212",
          "name":"basic toe touch (male)",
          "target":"glutes",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"rope",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0128.gif",
          "id":"0128",
          "name":"battling ropes",
          "target":"delts",
          },
          {
          "bodyPart":"cardio",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3360.gif",
          "id":"3360",
          "name":"bear crawl",
          "target":"cardiovascular system",
          },
          {
          "bodyPart":"chest",
          "equipment":"assisted",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1259.gif",
          "id":"1259",
          "name":"behind head chest stretch",
          "target":"chest",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0129.gif",
          "id":"0129",
          "name":"bench dip (knees bent)",
          "target":"triceps",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1399.gif",
          "id":"1399",
          "name":"bench dip on floor",
          "target":"triceps",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0130.gif",
          "id":"0130",
          "name":"bench hip extension",
          "target":"glutes",
          },
          {
          "bodyPart":"back",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3019.gif",
          "id":"3019",
          "name":"bench pull-ups",
          "target":"lats",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3639.gif",
          "id":"3639",
          "name":"bent knee lying twist (male)",
          "target":"glutes",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1770.gif",
          "id":"1770",
          "name":"biceps leg concentration curl",
          "target":"biceps",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0139.gif",
          "id":"0139",
          "name":"biceps narrow pull-ups",
          "target":"biceps",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0140.gif",
          "id":"0140",
          "name":"biceps pull-up",
          "target":"biceps",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0137.gif",
          "id":"0137",
          "name":"body-up",
          "target":"triceps",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3543.gif",
          "id":"3543",
          "name":"bodyweight drop jump squat",
          "target":"glutes",
          },
          {
          "bodyPart":"waist",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3544.gif",
          "id":"3544",
          "name":"bodyweight incline side plank",
          "target":"abs",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1771.gif",
          "id":"1771",
          "name":"bodyweight kneeling triceps extension",
          "target":"triceps",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1769.gif",
          "id":"1769",
          "name":"bodyweight side lying biceps curl",
          "target":"biceps",
          },
          {
          "bodyPart":"back",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3168.gif",
          "id":"3168",
          "name":"bodyweight squatting row",
          "target":"upper back",
          },
          {
          "bodyPart":"back",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3167.gif",
          "id":"3167",
          "name":"bodyweight squatting row (with towel)",
          "target":"upper back",
          },
          {
          "bodyPart":"lower legs",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1373.gif",
          "id":"1373",
          "name":"bodyweight standing calf raise",
          "target":"calves",
          },
          {
          "bodyPart":"back",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3156.gif",
          "id":"3156",
          "name":"bodyweight standing close-grip one arm row",
          "target":"upper back",
          },
          {
          "bodyPart":"back",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3158.gif",
          "id":"3158",
          "name":"bodyweight standing close-grip row",
          "target":"upper back",
          },
          {
          "bodyPart":"back",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3162.gif",
          "id":"3162",
          "name":"bodyweight standing one arm row",
          "target":"upper back",
          },
          {
          "bodyPart":"back",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3161.gif",
          "id":"3161",
          "name":"bodyweight standing one arm row (with towel)",
          "target":"upper back",
          },
          {
          "bodyPart":"back",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3166.gif",
          "id":"3166",
          "name":"bodyweight standing row",
          "target":"upper back",
          },
          {
          "bodyPart":"back",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3165.gif",
          "id":"3165",
          "name":"bodyweight standing row (with towel)",
          "target":"upper back",
          },
          {
          "bodyPart":"waist",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0138.gif",
          "id":"0138",
          "name":"bottoms-up",
          "target":"abs",
          },
          {
          "bodyPart":"lower legs",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1374.gif",
          "id":"1374",
          "name":"box jump down with one leg stabilization",
          "target":"calves",
          },
          {
          "bodyPart":"waist",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/2466.gif",
          "id":"2466",
          "name":"bridge - mountain climber (cross body)",
          "target":"abs",
          },
          {
          "bodyPart":"cardio",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1160.gif",
          "id":"1160",
          "name":"burpee",
          "target":"cardiovascular system",
          },
          {
          "bodyPart":"waist",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0870.gif",
          "id":"0870",
          "name":"butt-ups",
          "target":"abs",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"body weight",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1494.gif",
          "id":"1494",
          "name":"butterfly yoga pose",
          "target":"adductors",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0148.gif",
          "id":"0148",
          "name":"cable alternate shoulder press",
          "target":"delts",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0149.gif",
          "id":"0149",
          "name":"cable alternate triceps extension",
          "target":"triceps",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/3235.gif",
          "id":"3235",
          "name":"cable assisted inverse leg curl",
          "target":"hamstrings",
          },
          {
          "bodyPart":"back",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0150.gif",
          "id":"0150",
          "name":"cable bar lateral pulldown",
          "target":"lats",
          },
          {
          "bodyPart":"chest",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0151.gif",
          "id":"0151",
          "name":"cable bench press",
          "target":"chest",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1630.gif",
          "id":"1630",
          "name":"cable close grip curl",
          "target":"biceps",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1631.gif",
          "id":"1631",
          "name":"cable concentration curl",
          "target":"biceps",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0152.gif",
          "id":"0152",
          "name":"cable concentration extension (on knee)",
          "target":"triceps",
          },
          {
          "bodyPart":"back",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0153.gif",
          "id":"0153",
          "name":"cable cross-over lateral pulldown",
          "target":"lats",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0154.gif",
          "id":"0154",
          "name":"cable cross-over revers fly",
          "target":"delts",
          },
          {
          "bodyPart":"chest",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0155.gif",
          "id":"0155",
          "name":"cable cross-over variation",
          "target":"chest",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0868.gif",
          "id":"0868",
          "name":"cable curl",
          "target":"biceps",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0157.gif",
          "id":"0157",
          "name":"cable deadlift",
          "target":"glutes",
          },
          {
          "bodyPart":"chest",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0158.gif",
          "id":"0158",
          "name":"cable decline fly",
          "target":"chest",
          },
          {
          "bodyPart":"chest",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1260.gif",
          "id":"1260",
          "name":"cable decline one arm press",
          "target":"chest",
          },
          {
          "bodyPart":"chest",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1261.gif",
          "id":"1261",
          "name":"cable decline press",
          "target":"chest",
          },
          {
          "bodyPart":"back",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0159.gif",
          "id":"0159",
          "name":"cable decline seated wide-grip row",
          "target":"upper back",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1632.gif",
          "id":"1632",
          "name":"cable drag curl",
          "target":"biceps",
          },
          {
          "bodyPart":"back",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0160.gif",
          "id":"0160",
          "name":"cable floor seated wide-grip row",
          "target":"upper back",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0161.gif",
          "id":"0161",
          "name":"cable forward raise",
          "target":"delts",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0162.gif",
          "id":"0162",
          "name":"cable front raise",
          "target":"delts",
          },
          {
          "bodyPart":"shoulders",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0164.gif",
          "id":"0164",
          "name":"cable front shoulder raise",
          "target":"delts",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0165.gif",
          "id":"0165",
          "name":"cable hammer curl (with rope)",
          "target":"biceps",
          },
          {
          "bodyPart":"upper arms",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1722.gif",
          "id":"1722",
          "name":"cable high pulley overhead tricep extension",
          "target":"triceps",
          },
          {
          "bodyPart":"back",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0167.gif",
          "id":"0167",
          "name":"cable high row (kneeling)",
          "target":"upper back",
          },
          {
          "bodyPart":"upper legs",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0168.gif",
          "id":"0168",
          "name":"cable hip adduction",
          "target":"adductors",
          },
          {
          "bodyPart":"chest",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0169.gif",
          "id":"0169",
          "name":"cable incline bench press",
          "target":"chest",
          },
          {
          "bodyPart":"back",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/1318.gif",
          "id":"1318",
          "name":"cable incline bench row",
          "target":"upper back",
          },
          {
          "bodyPart":"chest",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0171.gif",
          "id":"0171",
          "name":"cable incline fly",
          "target":"chest",
          },
          {
          "bodyPart":"chest",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0170.gif",
          "id":"0170",
          "name":"cable incline fly (on stability ball)",
          "target":"chest",
          },
          {
          "bodyPart":"back",
          "equipment":"cable",
          "gifUrl":"http://d205bpvrqc9yn1.cloudfront.net/0172.gif",
          "id":"0172",
          "name":"cable incline pushdown",
          "target":"lats",
          },
      ]
   )
}